AWSTemplateFormatVersion: "2010-09-09"

Description: >
  Creates a pipeline that checks changes from git repo, performs a maven build, performs a docker build, pushes to ECR. Define registry and ecs task and service definition. Uses the stack-name for id collision prevention


Parameters:
  qsPipelineName:
    Description: The name of the AWS Code Pipeline
    Type: String
    Default: WG-ecr-pipe
    MinLength: 1
  qsPipelineRoleARN:
    Description: The complete ARN to the IAM role that code pipeline should use
    Type: String
    MinLength: 1
  qsCodeRepo:
    Description: The Code Repository
    Type: String
    MinLength: 1
  qsRepoBranch:
    Description: The Branch in the Repository
    Type: String
    MinLength: 1
  qsGitHubUser:
    Description: The GitHub User Id
    Type: String
    MinLength: 1
  qsGitHubAPIToken:
    Description: The GitHub Personal Access token do not use password
    NoEcho: true
    Type: String
    MinLength: 1
  qsS3PipelineArtifacts:
    Description: Where Code Pipeline will state artifacts in S3
    Type: String
    MinLength: 1
  qsCodeBuildName:
    Description: Name of the AWS Code Build Step
    Type: String
    Default: WG-mvnBuild
    MinLength: 1
  qsDockerBuildName:
    Description: Name of the AWS Code Build Docker Step
    Type: String
    Default: WG-Docker
    MinLength: 1
  qsKMSKeyARN:
    Description: The KMS ARN that the IAM Role is allowed to use
    Type: String
    MinLength: 1
  qsCodeRoleArn:
    Description: The IAM Role ARN for CodePipeline and CodeDeploy
    Type: String
    MinLength: 1
  qsECRrepositoryName:
    Description: The The name for the ECR repository
    Default: webgoatcd
    Type: String
    MinLength: 1
  qsECSserviceroleRoleARN:
    Description: The complete ARN to the IAM role/instance profile for the cluster
    Type: String
    MinLength: 1



Resources:
# ECR Setup
  stkECRrepo:
    Type: "AWS::ECR::Repository"
    Properties:
      RepositoryName: !Ref 'qsECRrepositoryName'




# Pipeline Items

  stkcbrCodeBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: Builds WebGoat Jar using build file in repo
      EncryptionKey: !Ref 'qsKMSKeyARN'
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/java:openjdk-8
        Type: LINUX_CONTAINER
      Name: !Ref 'qsCodeBuildName'
      ServiceRole: !Ref 'qsCodeRoleArn'
      TimeoutInMinutes: 10
      Source:
        Type: CODEPIPELINE



  stkcbrCodeBuildDocker:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: Builds WebGoat Container image using built jar and docker file
      EncryptionKey: !Ref 'qsKMSKeyARN'
      TimeoutInMinutes: 10
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            build:
              commands:
                - ls -la
                - $(aws ecr get-login)
                - docker build --tag ${ECRREPO}:latest .
                - docker push ${ECRREPO}:latest
                - echo $CODEBUILD_RESOLVED_SOURCE_VERSION  > dkrbuild.txt
          artifacts:
            files: 
              - dkrbuild.txt
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/docker:1.12.1
        Type: LINUX_CONTAINER
        EnvironmentVariables:
          - Name: AWSREGION
            Value: !Ref AWS::Region
          - Name: ECRREPO 
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${stkECRrepo}
      Name: !Ref 'qsDockerBuildName'
      ServiceRole: !Ref 'qsCodeRoleArn'


  stkcplPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Ref 'qsPipelineName'
      RoleArn: !Ref 'qsPipelineRoleARN'
      ArtifactStore:
        Location: !Ref 'qsS3PipelineArtifacts'
        Type: S3
      Stages:
        - Name: GetWGCode
          Actions:
            - Name: CodeSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              Configuration:
                Branch: !Ref 'qsRepoBranch'
                Repo: !Ref 'qsCodeRepo'
                Owner: !Ref 'qsGitHubUser'
                OAuthToken: !Ref 'qsGitHubAPIToken'
              OutputArtifacts:
                - Name: MySource
              RunOrder: '1'
        - Name: MvnBuildWG
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: MySource
              Configuration:
                ProjectName: !Ref stkcbrCodeBuild
              OutputArtifacts:
                - Name: MyBuild
              RunOrder: '1'
        - Name: DockerBuildWG
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: MyBuild
              Configuration:
                ProjectName: !Ref stkcbrCodeBuildDocker
              OutputArtifacts:
                - Name: MyResult
              RunOrder: '1'







Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${stkcplPipeline}
  ImageRepo:
    Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${stkECRrepo}

